=== Trilarion/freerails/src/main/resources/freerails/data/cargo_and_terrain.dtd
<!--
  ~ FreeRails
  ~ Copyright (C) 2000-2018 The FreeRails Team
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

        <!ELEMENT Cargo EMPTY>
        <!ATTLIST Cargo
                Category (Mail | Passengers | Fast_Freight  | Slow_Freight  | Bulk_Freight  ) #REQUIRED
                id ID #REQUIRED
                unitWeight ( 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 ) #REQUIRED
                >

        <!ELEMENT Cargo_Types (Cargo)*>

        <!ELEMENT Consumes EMPTY>
        <!ATTLIST Consumes
                Prerequisite ( 1 | 2 | 4 | 8 | 16 )  #IMPLIED
                Cargo IDREF #REQUIRED
                >

        <!ELEMENT Converts EMPTY>
        <!ATTLIST Converts
                input IDREF #REQUIRED
                output IDREF #REQUIRED
                >

        <!ELEMENT Produces EMPTY>
        <!ATTLIST Produces
                Cargo IDREF #REQUIRED
                Rate CDATA #REQUIRED
                >

        <!ELEMENT Terrain_Types (Tile)*>

        <!ELEMENT Tile (Converts|Consumes|Produces)*>
        <!ATTLIST Tile
                Category (Urban | River | Ocean | Hill | Country | Special | Industry | Resource) #REQUIRED
                right-of-way CDATA #REQUIRED
                build_cost CDATA #IMPLIED
                rgb CDATA #REQUIRED
                id ID #REQUIRED
                >

        <!ELEMENT Types (Cargo_Types, Terrain_Types)>

=== Trilarion/freerails/src/main/resources/freerails/data/cargo_and_terrain.xml
<!--
  ~ FreeRails
  ~ Copyright (C) 2000-2018 The FreeRails Team
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!DOCTYPE Types SYSTEM "cargo_and_terrain.dtd">
<Types>
    <Cargo_Types>
        <Cargo id="Mail" Category="MAIL" unitWeight="1"/>

        <Cargo id="Passengers" Category="PASSENGER" unitWeight="2"/>

        <Cargo id="Food" Category="FAST_FREIGHT" unitWeight="2"/>

        <Cargo id="Livestock" Category="FAST_FREIGHT" unitWeight="3"/>

        <Cargo id="Mfg._Goods" Category="FAST_FREIGHT" unitWeight="3"/>

        <Cargo id="Grain" Category="SLOW_FREIGHT" unitWeight="5"/>

        <Cargo id="Coffee" Category="SLOW_FREIGHT" unitWeight="5"/>

        <Cargo id="Export_Goods" Category="SLOW_FREIGHT" unitWeight="5"/>

        <Cargo id="Petroleum" Category="BULK_FREIGHT" unitWeight="8"/>

        <Cargo id="Oil" Category="BULK_FREIGHT" unitWeight="8"/>

        <Cargo id="Wood" Category="BULK_FREIGHT" unitWeight="8"/>

        <Cargo id="Sugar" Category="BULK_FREIGHT" unitWeight="8"/>
    </Cargo_Types>

    <Terrain_Types>
        <Tile id="City" Category="URBAN" rgb="ef901e" right-of-way="0">
            <Produces Cargo="Mail" Rate="40"/>

            <Produces Cargo="Passengers" Rate="80"/>

            <Consumes Cargo="Mail" Prerequisite="2"/>

            <Consumes Cargo="Passengers" Prerequisite="2"/>

            <Consumes Cargo="Mfg._Goods" Prerequisite="2"/>

            <Consumes Cargo="Food" Prerequisite="2"/>
        </Tile>

        <Tile id="Refinery" Category="INDUSTRY" rgb="7" right-of-way="0" build_cost="300000">
            <Converts input="Oil" output="Petroleum"/>
        </Tile>
        <!-- Don't include slums for now, LL
              <Tile id="slums" Category="Urban" rgb="0" right-of-way="0"/>
        -->
        <Tile id="Village" Category="URBAN" rgb="d86c48" right-of-way="0">
            <Produces Cargo="Mail" Rate="10"/>

            <Produces Cargo="Passengers" Rate="40"/>

            <Consumes Cargo="Mfg._Goods" Prerequisite="4"/>

            <Consumes Cargo="Mail" Prerequisite="4"/>

            <Consumes Cargo="Passengers" Prerequisite="4"/>
        </Tile>

        <Tile id="Factory" Category="INDUSTRY" rgb="0000b7" right-of-way="1000" build_cost="600000">
            <Converts input="Coffee" output="Export_Goods"/>

            <Converts input="Wood" output="Export_Goods"/>

            <Converts input="Sugar" output="Export_Goods"/>

            <Converts input="Petroleum" output="Export_Goods"/>
        </Tile>

        <Tile id="Clear" Category="COUNTRY" rgb="00b400" right-of-way="0"/>

        <Tile id="Farm" Category="COUNTRY" rgb="48fc48" right-of-way="0"/>

        <Tile id="Desert" Category="COUNTRY" rgb="b42400" right-of-way="0"/>

        <Tile id="Ocean" Category="OCEAN" rgb="0000b4" right-of-way="0"/>

        <Tile id="Harbour" Category="OCEAN" rgb="1eead2" right-of-way="0">
            <Produces Cargo="Mail" Rate="40"/>

            <Produces Cargo="Passengers" Rate="40"/>

            <Produces Cargo="Mfg._Goods" Rate="160"/>

            <Converts input="Grain" output="Food"/>

            <Converts input="Export_Goods" output="Mfg._Goods"/>

            <Consumes Cargo="Grain"/>

            <Consumes Cargo="Coffee"/>

            <Consumes Cargo="Wood"/>

            <Consumes Cargo="Sugar"/>
        </Tile>

        <Tile id="Stock-Yard" Category="INDUSTRY" rgb="3" right-of-way="0" build_cost="200000">
            <Converts input="Livestock" output="Food"/>
        </Tile>

        <Tile id="Food_Proc._Plant" Category="INDUSTRY" rgb="5" right-of-way="0" build_cost="200000">
            <Converts input="Grain" output="Food"/>
        </Tile>

        <Tile id="Cattle_Ranch" Category="RESOURCE" rgb="4" right-of-way="0">
            <Produces Cargo="Livestock" Rate="160"/>
        </Tile>

        <Tile id="Grain_Elevator" Category="RESOURCE" rgb="fcfc48" right-of-way="0">
            <Produces Cargo="Grain" Rate="160"/>
        </Tile>

        <Tile id="Oil_Well" Category="RESOURCE" rgb="ef901d" right-of-way="0">
            <Produces Cargo="Oil" Rate="160"/>
        </Tile>

        <Tile id="Lumber_Mill" Category="RESOURCE" rgb="ef901c" right-of-way="0">
            <Produces Cargo="Wood" Rate="160"/>
        </Tile>

        <Tile id="Sugar_Plant." Category="RESOURCE" rgb="ef901f" right-of-way="0">
            <Produces Cargo="Sugar" Rate="160"/>
        </Tile>

        <Tile id="River" Category="RIVER" rgb="0048d8" right-of-way="0"/>

        <Tile id="Landing" Category="RIVER" rgb="0048d9" right-of-way="0">
            <Consumes Cargo="Grain"/>

            <Consumes Cargo="Coffee"/>

            <Consumes Cargo="Export_Goods"/>

            <Consumes Cargo="Wood"/>

            <Consumes Cargo="Sugar"/>
        </Tile>

        <Tile id="Terminal" Category="SPECIAL" rgb="1" right-of-way="0"/>

        <Tile id="Jungle" Category="COUNTRY" rgb="4890fc" right-of-way="0"/>

        <Tile id="Hills" Category="HILL" rgb="b4b4b4" right-of-way="0"/>

        <Tile id="Foothills" Category="HILL" rgb="90d8fc" right-of-way="0"/>

        <Tile id="Mountain" Category="HILL" rgb="ffffff" right-of-way="0"/>
    </Terrain_Types>
</Types>
