=== Trilarion/freerails/src/main/resources/freerails/data/cities.dtd
<?xml version='1.0' encoding='utf-8' ?>
        <!-- DTD for a simple city -->

        <!ELEMENT Cities (City*)>
        <!ELEMENT City (name, x, y)>
        <!ATTLIST City
                name CDATA #REQUIRED
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

=== Trilarion/freerails/src/org/railz/data/small_south_america_cities.xml
<!DOCTYPE Tiles SYSTEM "cities.dtd">

<!--This file specifies the name and co-ordinates of the cities on a map-->

<Cities>
	<City name="Rio De Janeiro" x="180" y="151"/>
	<City name="Montevideo" x="129" y="196"/>
	<City name="Santiago" x="78" y="205"/>
	<City name="Lima" x="46" y="103"/>
	<City name="Caracus" x="92" y="11"/>
	<City name="Buenos Aires" x="124" y="196"/>
	<City name="Porto Alegre" x="146" y="179"/>
	<City name="Mar del Plata" x="125" y="207"/>
	<City name="Cordoba" x="100" y="186"/>
	<City name="Barranquilla" x="60" y="10"/>
	<City name="Salvador" x="200" y="109"/>
	<City name="San Jose" x="21" y="12"/>
	<City name="Manaus" x="107" y="63"/>
	<City name="Managua" x="13" y="4"/>
	<City name="Medelin" x="52" y="24"/>
	<City name="Cali" x="45" y="44"/>
</Cities>

=== Trilarion/freerails/src/main/resources/freerails/data/small_south_america_cities.xml
<!--
  ~ FreeRails
  ~ Copyright (C) 2000-2018 The FreeRails Team
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!DOCTYPE Tiles SYSTEM "cities.dtd">

<!--This file specifies the name and co-ordinates of the cities on a map-->

<Cities>

    <City name="Macapa" x="50" y="23"/>
    <City name="Belem" x="63" y="27"/>
    <City name="Sao Luis" x="80" y="35"/>
    <City name="Cuiaba" x="12" y="72"/>
    <City name="Miracema do Norte" x="50" y="50"/>
    <City name="Manaus" x="23" y="35"/>
    <City name="Macapa" x="50" y="23"/>
    <City name="Boa Vista" x="11" y="11"/>
    <City name="Paramaribo" x="48" y="3"/>
</Cities>
