=== Trilarion/freerails/src/jfreerails/data/track_tiles.dtd
<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE Tiles SYSTEM "Track_Tiles.dtd">

    <Tiles>
    ...
    </Tiles>
-->

  <!ELEMENT CanOnlyBuildOnTheseTerrainTypes (TerrainType)*>

  <!ELEMENT CannotBuildOnTheseTerrainTypes (TerrainType)*>
  
  <!ELEMENT ListOfTrackPieceTemplates (TrackPieceTemplate)*>

  <!ELEMENT LegalRouteAcrossNode EMPTY>
  <!ATTLIST LegalRouteAcrossNode
    RouteTemplate CDATA #REQUIRED
  >

  <!ELEMENT ListOfLegalRoutesAcrossNode (LegalRouteAcrossNode)*>



  <!ELEMENT Tiles (TrackSet)>

  <!ELEMENT TerrainType EMPTY>
  <!ATTLIST TerrainType
    name CDATA #REQUIRED
  >

  <!ELEMENT TrackType ((CannotBuildOnTheseTerrainTypes|CanOnlyBuildOnTheseTerrainTypes),ListOfTrackPieceTemplates)>
  <!ATTLIST TrackType
    RGBvalue CDATA #REQUIRED
    doubleTrack (true|false)  #REQUIRED
    maxConsecuativePieces CDATA #REQUIRED
    station (true|false) #REQUIRED
    stationRadius (0|1|2|3) #IMPLIED
    type CDATA #REQUIRED
    Y CDATA #REQUIRED
    signalTower (true|false)  #REQUIRED
    X CDATA #REQUIRED
    price CDATA #REQUIRED
    maintenance CDATA #REQUIRED
  >

  <!ELEMENT TrackPieceTemplate (ListOfLegalRoutesAcrossNode)>
  <!ATTLIST TrackPieceTemplate
    trackTemplate CDATA #REQUIRED
  >

  <!ELEMENT TrackSet (TrackType)*>
  <!ATTLIST TrackSet
    Width CDATA #REQUIRED
    Class CDATA #REQUIRED
    Y CDATA #REQUIRED
    Height CDATA #REQUIRED
    X CDATA #REQUIRED
  >

=== Trilarion/freerails/src/jfreerails/data/track_tiles.xml
<!DOCTYPE Tiles SYSTEM "track_tiles.dtd">
<!--This file species the track (and station) types, and the legal track configurations for each of these types.-->
<Tiles>
   <TrackSet X="0" Y="0" Height="60" Width="60" Class="Track">
      <TrackType type="standard track" X="0" Y="0" signalTower="false" doubleTrack="false" station="false" maxConsecuativePieces="-1" RGBvalue="000000" price="10000" maintenance="1000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="Urban" />

            <TerrainType name="Country" />

            <TerrainType name="Special" />
         </CanOnlyBuildOnTheseTerrainTypes>

         <ListOfTrackPieceTemplates>
            <TrackPieceTemplate trackTemplate="010010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="000111000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010001">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010011">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010110">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010111010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010011000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="011010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010111000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>
         </ListOfTrackPieceTemplates>
      </TrackType>

      <TrackType type="double track" X="0" Y="15" signalTower="false" doubleTrack="true" station="false" maxConsecuativePieces="-1" RGBvalue="000001" price="20000" maintenance="2000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="Urban" />

            <TerrainType name="Country" />

            <TerrainType name="Special" />
         </CanOnlyBuildOnTheseTerrainTypes>

         <ListOfTrackPieceTemplates>
            <TrackPieceTemplate trackTemplate="010010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="000111000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010001">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010011">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010110">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010111010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>
         </ListOfTrackPieceTemplates>
      </TrackType>

      <TrackType type="tunnel" X="9" Y="0" signalTower="false" doubleTrack="false" station="false" maxConsecuativePieces="-1" RGBvalue="000002" price="40000" maintenance="2000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="Hill" />
         </CanOnlyBuildOnTheseTerrainTypes>

         <ListOfTrackPieceTemplates>
            <TrackPieceTemplate trackTemplate="010010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="000111000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>
         </ListOfTrackPieceTemplates>
      </TrackType>

      <TrackType type="wooden trestle bridge" X="9" Y="2" signalTower="false" doubleTrack="false" station="false" maxConsecuativePieces="-1" RGBvalue="000003" price="50000" maintenance="2000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="River" />
         </CanOnlyBuildOnTheseTerrainTypes>

         <ListOfTrackPieceTemplates>
            <TrackPieceTemplate trackTemplate="010010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="000111000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>
         </ListOfTrackPieceTemplates>
      </TrackType>

      <TrackType type="steel girder bridge" X="9" Y="4" signalTower="false" doubleTrack="false" station="false" maxConsecuativePieces="-1" RGBvalue="000004" price="100000" maintenance="2000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="River" />
         </CanOnlyBuildOnTheseTerrainTypes>

         <ListOfTrackPieceTemplates>
            <TrackPieceTemplate trackTemplate="010010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="000111000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>
         </ListOfTrackPieceTemplates>
      </TrackType>

      <TrackType type="stone masonry bridge" X="9" Y="6" signalTower="false" doubleTrack="false" station="false" maxConsecuativePieces="-1" RGBvalue="000005" price="200000" maintenance="2000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="River" />
         </CanOnlyBuildOnTheseTerrainTypes>

         <ListOfTrackPieceTemplates>
            <TrackPieceTemplate trackTemplate="010010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="000111000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>
         </ListOfTrackPieceTemplates>
      </TrackType>

      <TrackType type="signal tower" X="9" Y="8" signalTower="true" doubleTrack="false" station="false" maxConsecuativePieces="-1" RGBvalue="000006" price="25000" maintenance="2000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="Urban" />

            <TerrainType name="Country" />

            <TerrainType name="Special" />
         </CanOnlyBuildOnTheseTerrainTypes>

         <ListOfTrackPieceTemplates>
            <TrackPieceTemplate trackTemplate="010010000">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="000111000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>

            <TrackPieceTemplate trackTemplate="010010010">
               <ListOfLegalRoutesAcrossNode>
                  <LegalRouteAcrossNode RouteTemplate="010011000" />
               </ListOfLegalRoutesAcrossNode>
            </TrackPieceTemplate>
         </ListOfTrackPieceTemplates>
      </TrackType>

      <TrackType type="depot" X="9" Y="10" signalTower="true" doubleTrack="false" station="true" stationRadius="1" maxConsecuativePieces="-1" RGBvalue="000007" price="50000" maintenance="2000">
         <CanOnlyBuildOnTheseTerrainTypes>
            <TerrainType name="Urban" />
